Myblog2.0/app/models.py
from app import db
from flask.ext.login import UserMixin
from datetime import datetime
from markdown import markdown
from . import login_manager


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(64),unique=True)
    users = db.relationship('User',backref = 'role')

    def __repr__(self):
        return '<Role %r>' % self.name

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(64),unique=True,index=True)
    password = db.Column(db.String(64))
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'),default=3)

    posts = db.relationship('Post',backref ='author')

    def __repr__(self):
        return '<User %r>' % self.username


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String)
    body = db.Column(db.Text)
    body_html = db.Column(db.String)
    timestamp = db.Column(db.DateTime,index=True,default=datetime.utcnow())

    comments = db.relationship('Comment',backref = 'post')
    author_id = db.Column(db.Integer,db.ForeignKey('users.id'))

    @staticmethod
    def on_body_change(target,value,oldvalue,inititor):
        if value is None or (value is ''):
            target.body_html=''
        else:
            target.body_html = markdown(value)

db.event.listen(Post.body,'set',Post.on_body_change)

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer,primary_key=True)
    body = db.Column(db.String)
    created = db.Column(db.DateTime,index=True,default=datetime.utcnow())
    post_id = db.Column(db.Integer,db.ForeignKey('posts.id'))

class Board(db.Model):
    __tablename__= 'boards'
    id = db.Column(db.Integer,primary_key=True)
    body = db.Column(db.String)
    creater = db.Column(db.DateTime,index=True,default=datetime.utcnow())

Myblog2.0/app/main/forms.py
# coding:utf-8
from flask.ext.wtf import Form
from wtforms import StringField,SubmitField,TextAreaField
from flask.ext.pagedown.fields import PageDownField
from wtforms.validators import Required,Length,DataRequired

class PostForm(Form):
    title = StringField(label=u'标题',validators=[DataRequired()])
    body = PageDownField(label=u"内容",validators=[DataRequired()])
    submit = SubmitField(u'发表')


class CommentForm(Form):
    body = PageDownField(label=u'评论',validators=[DataRequired()])
    submit = SubmitField(u'发表')

class BoardForm(Form):
    body = PageDownField(label=u'内容',validators=[DataRequired()])
    submit = SubmitField(u'发表')

Myblog2.0/app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from flask_pagedown import PageDown
import os
from os import path

#from config import config


basedir = path.abspath(path.dirname(__file__))

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()
pagedown=PageDown()

def create_app(config_name):
    app = Flask(__name__)
    # app.config.from_object(config[config_name])
    # config[config_name].init_app(app)
    app.config['SECRET_KEY'] = 'leroy'
    app.config['SQLALCHEMY_DATABASE_URI'] = \
    'sqlite:///' + os.path.join(basedir, 'data.sqlite')
    app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN'] = True

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    pagedown.init_app(app)
    login_manager.init_app(app)
    from app.main import main as main_blueprint
    from app.auth import auth as auth_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint)

    return app

Myblog2.0/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

Myblog2.0/app/main/views.py
# coding:utf-8
from manage import db
from datetime import datetime
# import flask_login
from flask import render_template, abort, redirect, url_for, request
from flask.ext.login import login_required
from flask.ext.principal import Permission
from ..models import User, Post, Comment,Board
from .forms import PostForm, CommentForm,BoardForm
from . import main
from flask_login import current_user


@main.route('/')
def index():
    return render_template('index.html', title=u'欢迎来到我的博客')

@main.route('/wechat')
def wechat():
    return render_template('wechat.html')

@main.route('/board', methods=['GET','POST'])
def boards():
    page_index = request.args.get('page', 1, type=int)
    form = BoardForm()
    query = Board.query.order_by(Board.creater.desc())
    pagination = query.paginate(page_index, per_page=5, error_out=False)
    boards = pagination.items
    title = u'留言板'
    if form.validate_on_submit():
        board = Board(body = u'{}'.format(form.body.data))
        db.session.add(board)
        db.session.commit()
        return redirect(url_for('main.boards'))
    return render_template('board.html',form=form,title =title,boards=boards,pagination=pagination)


@main.route('/blog')
def blog():
    page_index = request.args.get('page', 1, type=int)
    query = Post.query.order_by(Post.timestamp.desc())
    pagination = query.paginate(page_index, per_page=5, error_out=False)
    posts = pagination.items
    return render_template('blog.html', title=u'个人博客', posts=posts, pagination=pagination)

@main.route('/aboutme')
def aboutme():
    title = u'关于我'
    return render_template('aboutme.html',
                           title=title)


@main.route('/posts/<int:id>', methods=['GET', 'POST'])
def posts(id):
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comments = Comment(body=form.body.data,
                           post_id=post.id)
        db.session.add(comments)
        db.session.commit()
    return render_template('post/detail.html',
                           form=form,
                           title=post.title,
                           post=post)


@main.route('/edit', methods=['GET', 'POST'])
@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id=0):
    form = PostForm()

    if id==0:
        post = Post(author_id=current_user)
    else:
        post = Post.query.filter_by(id=id).first()
    # print post
       # form.body.data = post.body
    if form.validate_on_submit():
        post = Post()
        post.body = form.body.data
        post.title = form.title.data
        post.author_id = current_user.id
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.index'))
    title = u'添加文章'
    if id > 0:
        title = u'编辑'

    return render_template('post/edit.html',
                       form=form,
                       title=title,
                       post=post)


@main.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    return render_template('user.html', user=user)


@main.errorhandler(404)
def page_not_found(errors):
    return render_template('404.html'), 404


@main.errorhandler(500)
def inter_server_error(errors):
    return render_template('500.html'), 500

@main.route('/nowtime')
def now_time():
    title = u'现在时间'
    return render_template('nowtime.html',
                           current_time=datetime.utcnow(),
                           title=title)


@main.route('/secret')
@login_required
def secret():
    if (current_user.is_authenticated):
        print "false"
    else:
        print "true"
    return render_template('secter.html')

Myblog2.0/app/templates/aboutme.html
{% extends 'base.html' %}
{% block scripts %}
    <script src="https://use.fontawesome.com/60b2e7c51c.js"></script>
{% endblock %}
{% block title %}关于我{% endblock %}
{% block page_content %}
    <div><div class="container">
        <p>&nbsp;&nbsp;&nbsp;&nbsp;我是Leroy（冯凯东），是东南大学成贤学院电子与计算机工程学院的一名大三在校生，
            将近三年的学习，使我学到了许多东西，当然 并不是多少与本专业有关的知识。利用大三的空余时间，我自学了Python这门语言，
            原来是想制作一个关于我们五个高中同学的网站，但是出去找实习工作的原因，我 选择了先制作这个个人博客，网站很简单，
            功能也并不是很完善，但至少能初步运行起来。后续我会陆续增加一些新的功能和机制</p>

       <p>&nbsp;&nbsp;&nbsp;&nbsp;关于这个网站，还有一个要感谢的人，他是我的同班同学、老乡navian，很多次遇到bug都是他教我如何调试
           如何排错，以至于我没有半途而废，<a href="http://118.89.26.239:8888">奈凡的网站</a>这个是他的个人网站。
        </p>
    </div>
        <div class="text-center">
            <img src="static/aboutme.JPG" class="img-responsive center-block" alt="Cinque Terre" width="300">
        </div>
    </div>
    <div class="text-center">
        <br>
        <a href="{{ url_for('main.wechat') }}"><i class="fa fa-weixin fa-2x" aria-hidden="true"></i></a>
        <a href="https://github.com/1er0y/study"><i class="fa fa-github fa-2x" aria-hidden="true"></i></a>
        <a href="https://www.facebook.com/profile.php?id=100013150865537"><i class="fa fa-facebook-square fa-2x" aria-hidden="true"></i></a>
    </div>
{% endblock %}

Myblog2.0/app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
{% endblock %}

{% block head %}
    {{ super() }}
{#    <link href="{{ url_for('static',filename='site.css') }}" rel="stylesheet"/>#}
{% endblock %}

{% block title %}Leroy{% endblock %}
{% block navbar %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Leroy</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li class="active">
            <a href="{{ url_for('main.index') }}">主页<span class="sr-only">(current)</span></a></li>
        <li><a href="{{ url_for('main.blog') }}">博客</a></li>
        <li><a href="{{ url_for('main.aboutme') }}">关于我</a></li>
        <li><a href="{{ url_for('main.boards') }}">留言板</a></li>
{#        <li class="dropdown">#}
{#            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">菜单<span class="caret"></span></a>#}
{#          <ul class="dropdown-menu" role="menu">#}
{#            <li><a href="{{ url_for('auth.register') }}">注册</a></li>#}
{#            <li><a href="#">Another action</a></li>#}
{#            <li><a href="#">Something else here</a></li>#}
{#            <li class="divider"></li>#}
{#            <li><a href="#">Separated link</a></li>#}
{#            <li class="divider"></li>#}
{#            <li><a href="#">One more separated link</a></li>#}
{#          </ul>#}
{#        </li>#}
      </ul>
{#      <form class="navbar-form navbar-left" role="search">#}
{#        <div class="form-group">#}
{#          <input type="text" class="form-control" placeholder="Search">#}
{#        </div>#}
{#        <button type="submit" class="btn btn-default">Submit</button>#}
{#      </form>#}
      <ul class="nav navbar-nav navbar-right">
          {% if not current_user.is_authenticated %}
              <li><a href="{{ url_for('auth.login') }}">登录</a></li>
{#              <li><a href="{{ url_for('auth.register') }}">注册</a> </li>#}
          {% else %}
              <li><a href="{{ url_for('auth.logout') }}">注销</a></li>
              <li><a href="#">{{ current_user.username }}</a></li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    <div class="page-header">
        <h1 class="text-center">{{ title }}</h1>
    </div>
    {% for message in get_flashed_messages() %}
    <div class="alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    </div>
    {% block page_content %}
    {% endblock %}
    {% block foot %}
        <hr>
        <div class="text-center">
            <p>copyright by<a href="#">Leroy</a></p>
        </div>
    {% endblock %}
</div>
{% endblock %}

Myblog2.0/app/templates/blog.html
{% extends 'base.html' %}
{% from "bootstrap/pagination.html" import render_pagination %}
{% block title %}博客{% endblock %}

{% block page_content %}
    <div class="center-block">
    {% for post in posts %}
        <div class="text-center">
        <h2><a href="{{ url_for('main.posts',id = post.id) }}">{{ post.title }}</a></h2>
        </div>
        <div>
        {{ post.body_html|safe }}
        </div>
    </div>
    {% endfor %}
    <div class="text-center">
        <div class="center-block">
            {% if pagination %}
                {{ render_pagination(pagination) }}
            {% endif %}
         </div>
    </div>

{% endblock %}

Myblog2.0/app/templates/board.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "bootstrap/pagination.html" import render_pagination %}
{% block title%}留言本{% endblock %}

{% block page_content %}
    <div class="container">
         <form method="post">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.body(only_input=True,rows=4,class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary pull-right")}}
            </div>
        </form>
    </div>
    <div class="container">
        {% for board in boards|sort(attribute="creater",reverse=True) %}
        <div class="media">
            <hr>
            <span>留言日期:{{ moment(board.creater).format('LLL') }}</span>
                <div class="media-body">
                    <p>{{ board.body }}</p>
                </div>
        </div>
        {% endfor %}
        <div class="text-center">
            <div class="center-block">
                {% if pagination %}
                    {{ render_pagination(pagination) }}
                {% endif %}
             </div>
        </div>
    </div>

{% endblock %}

Myblog2.0/app/templates/include/_head.html
{#    <meta charset="UTF-8">#}
{#    <link href="{{ url_for('static',filename='site.css') }}" rel="stylesheet">#}
{#    <title>{% block title %}Title{% endblock %}</title>#}

Myblog2.0/app/templates/index.html
{% extends 'base.html' %}
{% block title %}Leroy{% endblock %}

{% block page_content %}
    <div class="container">
        <h2 class="text-center">二狗的世界欢迎你！</h2>
    </div>

{% endblock %}

Myblog2.0/app/templates/login.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Login{% endblock %}

{% block page_content %}
    <div class="container">
    {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

Myblog2.0/app/templates/logout.html
{% extends 'base.html' %}

{% block title %}注销{% endblock %}

{% block page_content %}
    <div class="page-header">
        <div class="container">
        <h1>注销成功！</h1>
        </div>
    </div>
{% endblock %}

Myblog2.0/app/templates/nowtime.html
{% extends 'base.html' %}

{% block title %}Now Time{% endblock %}
{% block page_content %}
    <div class="page-header">
        <h1>当地时间{{ moment(current_time).format('LLL') }}.</h1>
        <h1>刚才开始已经过去{{ moment(current_time).fromNow(refresh=True) }}</h1>
    </div>
{% endblock %}

Myblog2.0/app/templates/post/detail.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <div class="container">
        <span>发表日期:{{ moment(post.timestamp).format('LLL') }}</span>
        <hr>

        {# 正文 #}
        <div>
            {{ post.body_html|safe }}
        </div>

        {# 操作链接 #}
        <h3>评论</h3>
        {# 发表评论 #}
        <div>
            {{ wtf.quick_form(form) }}
        </div>

        {# 评论列表 #}
        {% for comment in post.comments|sort(attribute="created",reverse=True) %}
        <div class="media">
{#            <div class="media-left">#}
{#                <a href="#">#}
{#                    <img class="media-object" src="">#}
{#                </a>#}
{#            </div>#}
                <span>评论日期:{{ moment(comment.created).fromNow(refresh=True) }}</span>
                <div class="media-body">
                {{ comment.body }}
                </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

Myblog2.0/app/templates/post/edit.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block scripts %}
    {{ super() }}
    {{ pagedown.include_pagedown() }}
{% endblock %}

{% block page_content %}
    <div class="container">
        <form method="post">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.title(class="form-control",placeholder="请输入文章标题") }}
            </div>
            <div class="form-group">
                {{ form.body(only_input=True,rows=12,class="form-control") }}
            </div>
            <div>
                {{ form.body(only_preview=True) }}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
{% endblock %}

Myblog2.0/app/templates/register.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}注册{% endblock %}

{% block page_content %}
  <div class="container">
        {{ wtf.quick_form(form) }}
  </div>
{% endblock %}

Myblog2.0/app/templates/secter.html
{% extends 'base.html' %}

{% block title %}一般人看不见呦！{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>登录之后可进入本页面</h1>
</div>
{% endblock %}

Myblog2.0/app/templates/user.html
{% extends 'base.html' %}

{% block title %}User,{{ username }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Hello,{{ username }}</h1>
    {% if user.name or user.location %}
    <p>
        {% if user.name %}{{ user.name }}{% endif %}
        {% if user.location %}
            From <a href="http://maps.google.com/?q={{ user.location }}">
                {{ user.location }}
                </a>
        {% endif %}
    </p>
    {% if current_user.is_administrator() %}
    <p>sss</p>
</div>

Myblog2.0/app/templates/wechat.html
{% extends 'base.html' %}

{% block title %}微信{% endblock %}

{% block page_content %}
    <img src="static/wechat.png" class="img-responsive center-block" alt="Cinque Terre" width="300">
{% endblock %}